### ISSUE TITLE
Repo title change?

### ISSUE THREAD

**Issue by leekelleher** [mindrevolution/Editor.js-for-Umbraco#4]
This is more of a question of personal preference.  With my repos for Umbraco projects, I tend to prefix with **"umbraco-"**, then the package name - all in lowercase.

The main reason I do this that it gives some context of the topic, e.g. it's an Umbraco project.
_Almost like a pseudo-taxonomy._  If I did other tech, I'd prefix those repos, so it'd be easier for me to find.

So for this repo, I'd go with **"umbraco-editorjs"**.

@esn303 What are your thoughts about this?

(Not a showstopper in the slightest. 😊)

**Comment by MarcStoecker** [comment]
I think that's a good idea and and did so as well in the past.

Why not here? Because I was **overly careful in regards to copyrights and trademarks**. If something is called "Widget for BMW", that's perfectly allowed (at least in the EU) and undisputable (trademark wise) if it actually is for BMWs. Whereas "BMW Widget" can suggest (in the opinion of i.e. attorneys and trademark owners) to a casual user that it's an official BMW product or _at least_ endorsed by them.

So, on second thought: I would be happy with the change and just risk it in this particular case ... 😉

**Comment by MarcStoecker** [comment]
Changed repo name, you may have to update your remote origin:
https://github.com/mindrevolution/umbraco-editorjs.git
*(I concluded to do it NOW instead of to wait as the URL changes; the quicker the better)*

**Comment by leekelleher** [comment]
Thanks @esn303!

Note taken about the copyright/trademarks - let's keep the official (display) title as "Editor.js for Umbraco". 🙏
